### ISSUE TITLE
efibootmgr-gui-git on AUR is broken

### ISSUE THREAD

**Issue by SamLukeYes** [Elinvention/efiboots#21]
```
==> Starting package()...
install: cannot stat '/var/tmp/pamac-build-yes/efibootmgr-gui-git/src/efibootmgr-gui/efibootmgr.desktop': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```
The PKGBUILD on AUR is broken due to recent commits. Please update it.

**Comment by Elinvention** [comment]
I think I correctly updated the PKGBUILD. I also sent an AUR merge request to rename the package from `efibootmgr-gui-git` to `efiboots-git`.
If you want I can add you as co-maintainer.

**Comment by SamLukeYes** [comment]
OK, I successfully built and installed `efiboots-git`, but unfortunately it doesn't launch:
```
$ efiboots
DEBUG:root:Running: findmnt --noheadings --output SOURCE,FSTYPE --mountpoint /efi
DEBUG:root:Running: findmnt --noheadings --output SOURCE,FSTYPE --mountpoint /boot/efi
DEBUG:root:Running: findmnt --noheadings --output SOURCE,FSTYPE --mountpoint /boot
DEBUG:root:Device path /dev/nvme0n1p1 split into /dev/nvme0n1 and 1
INFO:root:Detected ESP on disk /dev/nvme0n1 part 1
DEBUG:root:['BootCurrent: 000B', 'Timeout: 0 seconds', 'BootOrder: 0002,0004,000B,0005,000A,0003,0001,0006,0000', 'Boot0000* SurfaceFrontPage\tFvVol(a881d567-6cb0-4eee-8435-2e72d33e45b5)/FvFile(4042708a-0f2d-4823-ac60-0d77b3111889)VOL+.', 'Boot0001* Internal Storage\tFvVol(a881d567-6cb0-4eee-8435-2e72d33e45b5)/FvFile(50670071-478f-4be7-ad13-8754f379c62f)SDD.', 'Boot0002  USB Storage\tFvVol(a881d567-6cb0-4eee-8435-2e72d33e45b5)/FvFile(50670071-478f-4be7-ad13-8754f379c62f)USB.', 'Boot0003* PXE Network\tFvVol(a881d567-6cb0-4eee-8435-2e72d33e45b5)/FvFile(50670071-478f-4be7-ad13-8754f379c62f)PXE.', 'Boot0004  linux-surface (reboot=pci)\tHD(1,GPT,8b824cbb-3248-4aeb-8ca0-3073b5a41bc4,0x800,0x82000)/File(\\vmlinuz-linux-surface)r.o.o.t.=.L.A.B.E.L.=.r.o.o.t. .i.n.i.t.r.d.=.i.n.t.e.l.-.u.c.o.d.e...i.m.g. .i.n.i.t.r.d.=.i.n.i.t.r.a.m.f.s.-.l.i.n.u.x.-.s.u.r.f.a.c.e...i.m.g. .z.s.w.a.p...e.n.a.b.l.e.d.=.0. .r.e.b.o.o.t.=.p.c.i.', 'Boot0005* linux-mainline\tHD(1,GPT,8b824cbb-3248-4aeb-8ca0-3073b5a41bc4,0x800,0x82000)/File(\\vmlinuz-linux-mainline)r.o.o.t.=.L.A.B.E.L.=.r.o.o.t. .i.n.i.t.r.d.=.i.n.t.e.l.-.u.c.o.d.e...i.m.g. .i.n.i.t.r.d.=.i.n.i.t.r.a.m.f.s.-.l.i.n.u.x.-.m.a.i.n.l.i.n.e...i.m.g. .z.s.w.a.p...e.n.a.b.l.e.d.=.0.', 'Boot0006* Linux Firmware Updater\tHD(1,GPT,8b824cbb-3248-4aeb-8ca0-3073b5a41bc4,0x800,0x82000)/File(\\EFI\\arch\\fwupdx64.efi)', 'Boot000A* linux-zen\tHD(1,GPT,8b824cbb-3248-4aeb-8ca0-3073b5a41bc4,0x800,0x82000)/File(\\vmlinuz-linux-zen)r.o.o.t.=.L.A.B.E.L.=.r.o.o.t. ...i.n.i.t.r.d.=.i.n.t.e.l.-.u.c.o.d.e...i.m.g. .i.n.i.t.r.d.=.i.n.i.t.r.a.m.f.s.-.l.i.n.u.x.-.z.e.n...i.m.g. .z.s.w.a.p...e.n.a.b.l.e.d.=.0.', 'Boot000B* linux-surface\tHD(1,GPT,8b824cbb-3248-4aeb-8ca0-3073b5a41bc4,0x800,0x82000)/File(\\vmlinuz-linux-surface)r.o.o.t.=.L.A.B.E.L.=.r.o.o.t. ...i.n.i.t.r.d.=.i.n.t.e.l.-.u.c.o.d.e...i.m.g. .i.n.i.t.r.d.=.i.n.i.t.r.a.m.f.s.-.l.i.n.u.x.-.s.u.r.f.a.c.e...i.m.g. .z.s.w.a.p...e.n.a.b.l.e.d.=.0.']
DEBUG:parser:BootCurrent: 000B
DEBUG:parser:Timeout: 0
DEBUG:parser:BootOrder: ['0002', '0004', '000B', '0005', '000A', '0003', '0001', '0006', '0000']
Traceback (most recent call last):
  File "/usr/bin/efiboots", line 18, in <module>
    efiboots.run(parsed_args.disk, parsed_args.part)
  File "/usr/lib/python3.9/site-packages/efiboots.py", line 536, in run
    win = EFIWindow(f"--disk {disk} --part {part}")
  File "/usr/lib/python3.9/site-packages/efiboots.py", line 454, in __init__
    self.store.refresh()
  File "/usr/lib/python3.9/site-packages/efiboots.py", line 283, in refresh
    parsed_efi = parse_efibootmgr(boot)
  File "/usr/lib/python3.9/site-packages/efiboots.py", line 186, in parse_efibootmgr
    params = decode_efibootmgr(params)
  File "/usr/lib/python3.9/site-packages/efiboots.py", line 168, in decode_efibootmgr
    decoded = code_bytes.decode('utf-16')
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x2e in position 4: truncated data
```
Shall I open another issue?

**Comment by Elinvention** [comment]
I think the packaging issue is solved, so this issue can be closed. For that other error I committed a fix and you can open a new issue if there are other problems. Thanks!
