### ISSUE TITLE
Can't Launch Xubuntu 21.10

### ISSUE THREAD

**Issue by Diacius** [Elinvention/efiboots#33]
When the script is run this happens:
```
Traceback (most recent call last):
  File "/home/george/efiboots/efiboots", line 6, in <module>
    import efiboots
  File "/home/george/efiboots/efiboots.py", line 9, in <module>
    gi.require_version('Gtk', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0
```
I did some research and it's because the Gtk 4.0 libraries are unavailable on Ubuntu. Any suggestions?

**Comment by Elinvention** [comment]
Well, I think you should [install Gtk 4.0 libraries](https://www.gtk.org/docs/installations/linux). I will update the README.
